name: train_badminton
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  fl_chart: ^0.66.1
  table_calendar: ^3.0.8
  cupertino_icons: ^1.0.2
  syncfusion_flutter_charts: ^24.2.3
  flutter_calendar_carousel: ^2.0.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/logo7.png
    - images/photo1.png
    - images/photoavg.png
    - images/photoplay.png

